server:
  port: 8082

spring:
  data:
    redis:
      host: localhost
      port: 6379
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yml
  mail:
    host: smtp.mailbox.org
    port: 587
    username: admin
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    config:
      enabled: false

eureka:
  client:
    enabled: false

kafka:
  configuration:
    bootstrap-servers:
      - localhost:29092
      - localhost:39092
    group-id: mail-sender
    client-id: notification-service
    topics: email-notification
    sr-url: http://localhost:8081

scheduler:
  enabled: true
  delay: PT10S
  batchSize: 5
  lockAtLeastFor: PT10S
  lockAtMostFor: PT50S