spring:
  application:
    name: user-service
  profiles:
    active: dev
  cloud:
    config:
      enabled: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yml

management:
  endpoint:
    refresh:
      enabled: true
    scheduler:
      roles: ACTUATOR

scheduler:
  enabled: true
  delay: 100