server:
  port: 8082
spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.mailbox.org
    port: 587
    username: admin
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

kafka:
  configuration:
    bootstrap-servers:
      - localhost:29092
      - localhost:39092
    group-id: mail-sender
    client-id: app-one
    topics: email-notification

scheduler:
  enabled: true
  delay: PT10S
  batchSize: 2
  lockAtLeastFor: PT10S
  lockAtMostFor: PT50S