spring:
  config:
    import: "configserver:"
  cloud:
    config:
      enabled: true
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}