spring:
  application:
    name: notification-service
  profiles:
    active: dev
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yml
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

scheduler:
  enabled: true
  delay: 100