services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./src/main/resources:/docker-entrypoint-initdb.d
      - /var/lib/postgresql/data
    ports:
      - "6543:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  application:
    build: ./
    image: module3_image
    container_name: module3_container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SERVER_PORT: 8080
      POSTGRES_HOST: postgres_container
      POSTGRES_PORT: 5432
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres