{
 "title": "My custom dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Failed request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "event_request_failed_total{request=\"fail\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "event_total{request=\"total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "job_timer_seconds_bucket{task=\"duration\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}