spring:
  application:
    name: aston-spring
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
hibernate:
  hbm2ddl:
    auto: update

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
hibernate:
  hbm2ddl:
    auto: create-drop

---
spring:
  config:
    activate:
      on-profile: test
hibernate:
  hbm2ddl:
    auto: create-drop