spring:
  application:
    name: aston-spring
  profiles:
    active: dev
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yml

---
server:
  port: ${SERVER_PORT}

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  hbm2ddl:
    auto: update
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

swagger:
  app-name: ${spring.application.name}
  app-description: User Api Example
  app-version: 1.0

---
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
hibernate:
  hbm2ddl:
    auto: validate
  dialect: org.hibernate.dialect.PostgreSQLDialect

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        orm:
#          jdbc:
#            bind: TRACE