CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    email varchar(255) UNIQUE NOT NULL,
    age int NOT NULL,
    created_at timestamp NOT NULL default current_timestamp,
    PRIMARY KEY (id)
);