server:
  shutdown: graceful

spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: ${configuration.user-service-uri}/users
              predicates:
                - Path=/users
              filters:
                - TokenRelay=gateway
            - id: notification-service
              uri: ${configuration.mail-service-uri}/mail
              predicates:
                - Path=/mail
              filters:
                - TokenRelay=gateway
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: oauth
            client-id: gateway
            client-secret: ${configuration.client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          oauth:
            issuer-uri: ${configuration.auth-server-uri}