server:
  port: 8080
  shutdown: graceful

configuration:
  user-service-url: lb://user-service
  mail-service-url: lb://notification-service
  auth-server-url: http://authorization-server
  client-secret: secret

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

spring:
  application:
    name: gateway-service
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-server
    gateway:
      server:
        webflux:
          trusted-proxies:
            - 127.0.0.1
            - 10.0.0.0/8
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
              predicates:
                - name: Path
                  args:
                    pattern: "'/'+serviceId+'/**'"
              filters:
                - name: CircuitBreaker
                  args:
                    name: serviceId
                - name: RewritePath
                  args:
                    regexp: "'/' + serviceId + '/?(?<remaining>.*)'"
                    replacement: "'/${remaining}'"

resilience4j.circuitbreaker:
  instances:
    UserService:
      registerHealthIndicator: true
      slidingWindowSize: 5
    NotificationService:
      registerHealthIndicator: true
      slidingWindowSize: 5

resilience4j.timelimiter:
  instances:
    UserService:
      timeoutDuration: 5s
      cancelRunningFuture: false
    NotificationService:
      timeoutDuration: 5s
      cancelRunningFuture: false