server:
  port: 8090
  shutdown: graceful

main:
  web-application-type: reactive

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
              predicates:
                - name: Path
                  args:
                    pattern: "'/'+serviceId+'/**'"
              filters:
                - name: CircuitBreaker
                  args:
                    name: serviceId
                - name: RewritePath
                  args:
                    regexp: "'/' + serviceId + '/?(?<remaining>.*)'"
                    replacement: "'/${remaining}'"
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/mail/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j.circuitbreaker:
  instances:
    UserService:
      registerHealthIndicator: true
      slidingWindowSize: 5
    NotificationService:
      registerHealthIndicator: true
      slidingWindowSize: 5

resilience4j.timelimiter:
  instances:
    UserService:
      timeoutDuration: 5s
      cancelRunningFuture: false
    NotificationService:
      timeoutDuration: 5s
      cancelRunningFuture: false