spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
              predicates:
                - name: Path
                  args:
                    pattern: "'/'+serviceId+'/**'"
              filters:
                - name: CircuitBreaker
                  args:
                    name: serviceId
                - name: RewritePath
                  args:
                    regexp: "'/' + serviceId + '/?(?<remaining>.*)'"
                    replacement: "'/${remaining}'"

resilience4j.circuitbreaker:
  instances:
    UserService:
      registerHealthIndicator: true
      slidingWindowSize: 5
    NotificationService:
      registerHealthIndicator: true
      slidingWindowSize: 5

resilience4j.timelimiter:
  instances:
    UserService:
      timeoutDuration: 5s
      cancelRunningFuture: false
    NotificationService:
      timeoutDuration: 5s
      cancelRunningFuture: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}