server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.cloud.gateway: TRACE

configuration:
  user-service-uri: http://localhost:8070
  mail-service-uri: http://localhost:8071
  auth-server-uri: http://127.0.0.1:9000
  client-secret: secret

spring:
  cloud:
    config:
      enabled: false

eureka:
  client:
    enabled: false