server:
  shutdown: graceful

spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: ${configuration.user-service-url}
              predicates:
                - Path=/users/**
              filters:
                - RewritePath=/users/(?<segment>.*), /users/$\{segment}
                - TokenRelay=
            - id: notification-service
              uri: ${configuration.mail-service-url}/mail
              predicates:
                - Path=/mail/**
              filters:
                - RewritePath=/mail/(?<segment>.*), /mail/$\{segment}
                - TokenRelay=
            - id: authorization-server
              uri: ${configuration.auth-server-url}
              predicates:
                - Path=/auth/**
              filters:
                - RewritePath=/auth/?(?<segment>.*), /$\{segment}
                - TokenRelay=
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: oauth
            client-id: gateway
            client-secret: ${configuration.client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          oauth:
            issuer-uri: ${configuration.auth-server-url}