
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
kafka:
  configuration:
    bootstrap-servers:
      - localhost:9092
    topic-name: email-notification
    scheduled: 10000

hibernate:
  hbm2ddl:
    auto: validate
  dialect: org.hibernate.dialect.PostgreSQLDialect

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        orm:
#          jdbc:
#            bind: TRACE