server:
  port: 8070

configuration:
  auth:
    auth-server-url: http://localhost:9000
    client-secret: verySecret
  services:
    mail-service-uri: http://localhost:8082
  kafka:
    enabled: false
    bootstrap-servers:
      - localhost:29092
      - localhost:39092
    topic-name: email-notification
    partitions: 1
    srUrl: http://localhost:8081
  scheduler:
    enabled: false
    delay: 3000

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:user-service-db
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yml
  cloud:
    config:
      enabled: false
    openfeign:
      oauth2:
        enabled: true
        clientRegistrationId: user-service
  security:
    oauth2:
      client:
        registration:
          user-service:
            provider: oauth
            client-id: user-service
            client-authentication-method: client_secret_basic
            client-secret: ${configuration.auth.client-secret}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          oauth:
            authorization-uri: ${configuration.auth.auth-server-url}/oauth2/authorize
            jwk-set-uri: ${configuration.auth.auth-server-url}/oauth2/jwks
            token-uri: ${configuration.auth.auth-server-url}/oauth2/token

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: placeholder

# disable kafka
integration:
  event-driven:
    enabled: false

# disable metrics
endpoints:
  metrics:
    enabled: false

management:
  endpoints:
    metrics:
      enabled: false