server:
  port: 8070

configuration:
  auth:
    auth-server-url: http://localhost:9000
    jwk-set-uri: ${configuration.auth.auth-server-url}/oauth2/jwks
    token-uri: ${configuration.auth.auth-server-url}/oauth2/token
    authorization-uri: ${configuration.auth.auth-server-url}/oauth2/authorize
    client-secret: verySecret
  services:
    mail-service-uri: http://localhost:8082
  kafka:
    enabled: false
    bootstrap-servers:
      - localhost:29092
      - localhost:39092
    topic-name: email-notification
    partitions: 1
    srUrl: http://localhost:8081
  scheduler:
    enabled: false
    delay: 3000

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none
  cloud:
    config:
      enabled: false

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: placeholder

# disable kafka
integration:
  event-driven:
    enabled: false

# disable metrics
endpoints:
  metrics:
    enabled: false
management:
  endpoints:
    metrics:
      enabled: false

hibernate:
  hbm2ddl:
    auto: validate
  dialect: org.hibernate.dialect.PostgreSQLDialect