server:
  port: 8090
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yml
  cloud:
    config:
      enabled: false

eureka:
  client:
    enabled: false

kafka:
  configuration:
    bootstrap-servers:
      - localhost:29092
      - localhost:39092
    topic-name: email-notification
    partitions: 1
    srUrl: http://localhost:8081

scheduler:
  delay: 3000

hibernate:
  hbm2ddl:
    auto: validate
  dialect: org.hibernate.dialect.PostgreSQLDialect

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,prometheus,metrics
#  endpoint:
#    prometheus:
#      access: read_only
#  metrics:
#    distribution.percentiles-histogram.http:
#      server.requests: true
#      client.requests: true
#  tracing:
#    enabled: true
#    sampling:
#      probability: 1.0
#  prometheus:
#    metrics:
#      export:
#        enabled: true


#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        orm:
#          jdbc:
#            bind: TRACE