spring:
  application:
    name: discovery-service
  profiles:
    active: dev
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

