server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.gateway: DEBUG

spring:
  security:
    user:
      name: admin
      password: admin
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: gateway
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://localhost:8080/login/oauth2/code/gateway"
              post-logout-redirect-uris:
                - "http://localhost:8080/logout"
              scopes:
                - "openid"
                - "profile"
                - "usersrv"
                - "mailsrv"
            require-authorization-consent: true
            require-proof-key: false