server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/dev/config-repo
          searchPaths: '{application}'

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/