server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Serggge/config-repo
          default-label: master
          search-paths: "{application}"

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/